theme: jekyll-theme-minimal
title: Senekrainian
description: VB - The New Face of Senekrainian-Americans
logo: https://user-images.githubusercontent.com/52472274/60607957-4891ae80-9d8c-11e9-9ce6-3d2c6c4f0761.jpg
